[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk"}
serde = { version = "1.0", default-features = false }
ndarray = { version = "0.16.0", default-features = false }
